### ISSUE TITLE
Deploy problem?

### ISSUE THREAD

**Issue by yoavram** [nadav-ram/wiki-food#7]
On the python anywhere website I get an error instead of a map:
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by yoavram** [comment]
maybe because the API key is now missing? you'd probably need to read it from an envvar

**Comment by nadav-ram** [comment]
I figured out what the problem is, pythonanywhere doesn't work properly with relative paths and requires you to use absolute paths. This was causing the `gmplot.html` file to be saved in the home directory instead of the project directory.
I temporarily fixed the problem with the API key and map path by manually editing the `render_map` file on pythonanywhere. I will make sure to save both of them using envvars asap.

**Comment by yoavram** [comment]
or you could get the relative path by calling `os.getcwd()`.

**Comment by nadav-ram** [comment]
unfortunately, `os.getcwd()` doesn't work in pythonanywhere but `os.path.dirname(os.path.abspath(__file__))` worked just fine

**Comment by yoavram** [comment]
Nice!
I keep getting “This page can't load Google Maps correctly.” in a pop up over the map at pythonanywhere.

**Comment by nadav-ram** [comment]
@yoavram this just happens because I am using a free api key and its limited. 
this can be avoided by creating a Google cloud account.

**Comment by yoavram** [comment]
how about using [cartopy](https://scitools.org.uk/cartopy/docs/latest/)?
or [OpenStreetMap](https://www.openstreetmap.org/#map=8/31.438/35.074)
